version: "3"
services:
    java:
        build: .
        tty: true
        ports:
          - "8000:8000"
        volumes:
            - ./sample:/java/sample
        logging:
          driver: json-file
          options:
            max-size: '5m'
            max-file: '1'
