version: "3"
services:
  app:
    build: .
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./app:/work/app
      - /work/app/node_modules
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "1"
